### ISSUE TITLE
Missing Error Handling and Resource Duplication Risk (app.js file)

### ISSUE THREAD

**Issue by Amansingh0807** [NodeJSEngineering/appwrite-node#3]
While reviewing the code for the database creation and data seeding, I found a couple of potential issues that could affect the stability and functionality of the application:

No Error Handling: Currently, the async functions (prepareDatabase, seedDatabase, getTodos) do not have any error handling. If there’s an issue with creating the database, collections, or documents, the process will fail silently without any feedback.

Potential Duplication of Resources: Each time the application is run, a new database and collection are created. This can result in multiple instances of the same database (TodosDB) and collection (Todos), causing potential duplication and confusion.

Steps to Reproduce:
Run the code multiple times without checking if the database or collection already exists.
Introduce an intentional error (e.g., incorrect project key) and observe the lack of error reporting.
Suggested Fixes:
Add Error Handling: Wrap the asynchronous code in try-catch blocks to capture and log errors when operations like creating databases, collections, and documents fail.

Check for Existing Resources: Before creating a new database or collection, check if they already exist. This will avoid unnecessary duplication and streamline the creation process.

**Comment by log1-codes** [comment]
@Amansingh0807 @sunny7899 I can fix this using the plain css . please assign me the task .

**Comment by sunny7899** [comment]
@Anurag-singh-thakur please create new issue for that.
